# STUDENT API REQUESTS 

POST http://localhost:8000/api/students
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "date_of_birth": "1990-01-01",
    "gender": "male",
    "address": "123 Main St",
    "phone_number": "123-456-7890"
}

###

GET http://localhost:8000/api/students
Content-Type: application/json


# TEACHER API REQUESTS


# STUDENT API REQUESTS


#CLASS API REQUESTS


#ENROLLMENT ROUTES
